app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_app:
    resource: '@AppBundle/Controller/ApiController.php'
    type: rest
    prefix: app/api/

api_disponibilidades:
    resource: '@AppBundle/Controller/ApiDisponibilidadController.php'
    type: rest
    prefix: app/api/
